server {
    listen 80;
    server_name glonass-bot.ru www.glonass-bot.ru localhost _;

    client_max_body_size 1000M;

    location = / {
        add_header Content-Type text/plain;
        return 200 "Nginx is running\nMinIO files: /local/\nAdminer: /adminer/\n";
    }

    location /local/ {
        proxy_pass http://minio:3456/local/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
        send_timeout 300;
    }

    location /adminer/ {
        proxy_pass http://adminer:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /adminer;

        proxy_connect_timeout 300;
        proxy_read_timeout 300;
        proxy_http_version 1.1;
    }
}
